repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        language: python_venv
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language: python_venv
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # - id: double-quote-string-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: pylint
        stages: [push]
        name: pylint
        language: system
        entry: pylint --fail-under=9 --fail-on=invalid-name,wrong-import-order,ungrouped-imports tool-manager
        pass_filenames: false
      - id: pytest
        name: Check pytest unit tests pass
        entry: pytest -vv --cov=. --cov-fail-under=0 --cov-report=term-missing --color=yes --code-highlight=yes --new-first --verbose
        pass_filenames: false
        language: system
        always_run: true
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
      - id: python-safety-dependencies-check
